theme: jekyll-theme-cayman
description: https://github.com/eitan-rosati
github_button_location_top_navbar: true
github_editme_path: https://github.com/eitan-rosati
github_url: https://github.com/eitan-rosati
github:
  url: https://github.com/eitan-rosati
